### ISSUE TITLE
Upgrading to Celery 5.0.0 breaks flower due to change in celery.bin.base module.

### ISSUE THREAD

**Issue by mbayabo** [mher/flower#1029]
If you run flower with Celery 5.0.0 or if you use the docker image, it will say it cannot import "Command".

1. ```pip install celery==5.0.0```
THEN
2. ```flower --version```
OR
3. ```flower -A proj --broker=redis://redis```
OR
4. ```flower```

![image](https://user-images.githubusercontent.com/18492353/94216329-f3abed80-fe93-11ea-887d-e411eb48694e.png)

The Command class is no longer part of the base module:
[https://docs.celeryproject.org/en/v5.0.0/reference/celery.bin.base.html](https://docs.celeryproject.org/en/v5.0.0/reference/celery.bin.base.html)

Which means it can no longer import and inherit **Command**:

```command.py
from __future__ import absolute_import
from __future__ import print_function

import os
import sys
import atexit
import signal
import logging

from pprint import pformat

from logging import NullHandler

from tornado.options import options
from tornado.options import parse_command_line, parse_config_file
from tornado.log import enable_pretty_logging
from celery.bin.base import Command

from . import __version__
from .app import Flower
from .urls import settings
from .utils import abs_path, prepend_url
from .options import DEFAULT_CONFIG_FILE, default_options


logger = logging.getLogger(__name__)


class FlowerCommand(Command):
    # ...
```

**Comment by ifokeev** [comment]
Same problem here

**Comment by eliorc** [comment]
Same problem here as well

**Comment by kdiri** [comment]
Same problem here also.

**Comment by packetflow** [comment]
Same for me, needed downgrade to 4.4.7

**Comment by zufj** [comment]
Same here, also had to downgrade sadly

**Comment by cesarFrias** [comment]
Same for me, dowgraded celery to 4.4.7 as @packetflow

**Comment by PedroCaicedoDev** [comment]
Same problem for me

**Comment by mbayabo** [comment]
Hello All,

A work around if you don't want to downgrade all of celery is to use a docker container for flower:

```
  flower:
    image: mher/flower
    command: ["--app your_app", "--url_prefix=flower", "--broker=redis://redis"]
    ports:
      - 5555:5555
    restart: unless-stopped
```

**Comment by waldner** [comment]
Why was the issue closed? Is this resolved?

**Comment by sogloarcadius** [comment]
This issue should not be closed because not solved

Regards

**Comment by mandarvaze** [comment]
@mbayabo @mher Please keep one of the #1031 or #1029 open.

**Comment by mbayabo** [comment]
> @mbayabo @mher Please keep one of the #1031 or #1029 open.

I didn't close this.

**Comment by chrisburr** [comment]
@mbayabo I guess you accidentally clicked the "close and comment" button https://github.com/mher/flower/issues/1029#event-3837160460 but you should be able to re-open this issue.

**Comment by mbayabo** [comment]
@chrisburr Oh I see.

**Comment by ale8193** [comment]
Same problem for me, even if I'm using the docker image. Should I use a specific tag?

> Hello All,
> 
> A work around if you don't want to downgrade all of celery is to use a docker container for flower:
> 
> ```
>   flower:
>     image: mher/flower
>     command: ["--app your_app", "--url_prefix=flower", "--broker=redis://redis"]
>     ports:
>       - 5555:5555
>     restart: unless-stopped
> ```

**Comment by ale8193** [comment]
I solved creating a custom docker image in which I install flower and celery (version 4.4.7) using pip and then using my docker image.

```
FROM python:3.8.2-slim-buster

RUN apt-get update && apt-get install -y gcc python3-dev

RUN pip install --no-cache-dir -Iv flower redis celery==4.4.7

EXPOSE 5555

ENTRYPOINT ["flower"]
```

**Comment by mher** [comment]
You can use `0.9.5` tag with docker image

**Comment by ale8193** [comment]
> You can use `0.9.5` tag with docker image

This one is working too. Thanks

**Comment by michaelefisher** [comment]
> You can use `0.9.5` tag with docker image

This gets around this issue but then we run into the permissions issue if using `persistent=True` (which I think is fixed in latest). Any workaround besides creating another `Dockerfile`?

**Comment by tritium01** [comment]
creating a docker image seems to connect but can't seem to access the GUI via localhost:5555 any clues?

**Comment by phracek** [comment]
I have the same issue:

```bash
Traceback (most recent call last):
  File "/usr/local/bin/flower", line 5, in <module>
    from flower.__main__ import main
  File "/usr/local/lib/python3.9/site-packages/flower/__main__.py", line 4, in <module>
    from flower.command import FlowerCommand
  File "/usr/local/lib/python3.9/site-packages/flower/command.py", line 17, in <module>
    from celery.bin.base import Command
ImportError: cannot import name 'Command' from 'celery.bin.base' (/usr/local/lib/python3.9/site-packages/celery/bin/base.py)

```

**Comment by realityJie** [comment]
when this problem can be solved

**Comment by pembo13** [comment]
Any plan to fix this? Anyone working on this? Or should should I attempt a PR? Or give up on Flower and upgrade Celery to 5?

**Comment by piotrgrundas** [comment]
If u are using a custom docker django/celery, image u can just install `celery<5` before launching flower. That's my current workaround 🤷 
```
    command:
      - /bin/bash
      - -c
      - |
        pip install "celery<5"
        flower --app=pnk.celery:app --loglevel=warning --url_prefix=flower
```

**Comment by stuaxo** [comment]
It looks like they moved celery to use `click.Command` instead of celerys own implementation, so this will need to be ported to use one of the new implementations. 


Have a look at the difference in [celery/bin/base.py](https://github.com/celery/celery/blob/master/celery/bin/base.py) between `master` and the `4.3` tag.

I guess making it use `CeleryCommand` will be a start, then add the changes needed to make it work with click.

**Comment by ThiefMaster** [comment]
I think all you need to do is implementing a click-style CLI for the subcommand; check [one of the core celery subcommands](https://github.com/celery/celery/blob/master/celery/bin/call.py) for an example.

**Comment by stuaxo** [comment]
That sounds good, it probably needs someone more familiar with the code than me, apart from just now I haven't used flower, or looked at the celery code for 5 years.

**Comment by pembo13** [comment]
> I think all you need to do is implementing a click-style CLI for the subcommand; check [one of the core celery subcommands](https://github.com/celery/celery/blob/master/celery/bin/call.py) for an example.

I started looking at this, but it's a bit out of my depth without pre-existing familiarity with flower's codebase:
- `vine` needs to be updated from `1.3.0` to `5.0.0`
- the command style is function based, and apparently incompatible with a class based approach
- flower runs code outside of `celery`

Maybe I'll try again later, but I'm too unfamiliar with both `click` and `flower` to be useful here, as much as I need `flower` in my workflow.

**Comment by pembo13** [comment]
Scratch what I just said, looks like `celery` has documented how to invoke flower, is that because someone's working on this already?

https://github.com/celery/celery/blob/master/docs/userguide/extending.rst#adding-new-program-celery-sub-commands

**Comment by pembo13** [comment]
Looks like it's not even possible in celery 5.0.2 to use the click system as a celery plugin due to not having [@with_plugins(iter_entry_points('celery.commands'))](https://github.com/celery/celery/blob/ffacfe3e384554d1eeaaeb84a4b8e45171122b18/celery/bin/celery.py#L74)

**Comment by boundaryfree** [comment]
I have the same issue working with celery 5.0.2

`Traceback (most recent call last):
  File "/usr/local/bin/flower", line 5, in <module>
    from flower.__main__ import main
  File "/usr/local/lib/python3.9/site-packages/flower/__main__.py", line 4, in <module>
    from flower.command import FlowerCommand
  File "/usr/local/lib/python3.9/site-packages/flower/command.py", line 17, in <module>
    from celery.bin.base import Command
ImportError: cannot import name 'Command' from 'celery.bin.base' (/usr/local/lib/python3.9/site-packages/celery/bin/base.py)`

**Comment by Kate-liu** [comment]
Same problem for me

**Comment by digitaldavenyc** [comment]
Also getting this issue. This temp fix of using a downgraded version of celery in a custom `Dockerfile` isn't something I feel ok going to production with.

**Comment by mdantonio** [comment]
I agree with you, I hope to be able to remove this temporary fix as soon as possible

**Comment by cse031sust02** [comment]
I am having the same issue!

```
Traceback (most recent call last):
  File "/home/talha/.local/share/virtualenvs/scaling-celery-6oDIcQ0v/bin/flower", line 5, in <module>
    from flower.__main__ import main
  File "/home/talha/.local/share/virtualenvs/scaling-celery-6oDIcQ0v/lib/python3.7/site-packages/flower/__main__.py", line 4, in <module>
    from flower.command import FlowerCommand
  File "/home/talha/.local/share/virtualenvs/scaling-celery-6oDIcQ0v/lib/python3.7/site-packages/flower/command.py", line 17, in <module>
    from celery.bin.base import Command
ImportError: cannot import name 'Command' from 'celery.bin.base' (/home/talha/.local/share/virtualenvs/scaling-celery-6oDIcQ0v/lib/python3.7/site-packages/celery/bin/base.py)
```

**Comment by singh-atenekom** [comment]
I also have same issue with celery > 4.4.7

**Comment by tlrh314** [comment]
+1

**Comment by nedludd0** [comment]
hello, are you planning to develop a fix? thanks

**Comment by danielvlla** [comment]
Is this issue closed?

**Comment by stuaxo** [comment]
See the comment above your own.

**Comment by ckarrie** [comment]
> A PR is about to be merged #1021
> We are looking forward testing it

as mentioned by @tramora the current workaround is using the fork of @avikam

```pip install https://github.com/avikam/flower/zipball/master#egg=flower```

**Comment by goetzc** [comment]
This PR should fix the issue when it gets merged: https://github.com/mher/flower/pull/1021

**Comment by sanderbrauwers** [comment]
same here

**Comment by stuaxo** [comment]
@sanderbrauwers consider testing the PR in the comment above your own, and confirming if it works for your use-case.

If it doesn't then report an issue on it.

**Comment by sknutsonsf** [comment]
When you expect a new release to pypi with Celery 5.0.x support? The PR #1021 was merged a few days go (3/17/21).

**Comment by mher** [comment]
Please test the master version and comment here. I will release a new version soon.

**Comment by stuaxo** [comment]
I'm trying this right now, and everything seems to be working, fantastic work.

**Comment by erikcw** [comment]
I've been running master for the last 24 hours and it seems to be working great!

**Comment by preeth1** [comment]
This is not working for me. My findings:
1. I spin up a new linux machine, install celery 5.0.5, install flower from the latest master (`pip install https://github.com/mher/flower/zipball/master#egg=flower`), and I notice that I am able to open flower, but it doesn't detect any of my workers. Then, I downgrade back to flower 0.9.7, it works great. 
2. If I spin up a new linux machine, install celery 5.0.5, install flower 0.9.7, it doesn't even open up flower

**Comment by pembo13** [comment]
I too have updated my dev machine to celery 5.0.5 and flower from the latest master (`pip install https://github.com/mher/flower/zipball/master#egg=flower`) 

1. the `flower` command doesn't work, had to use `celery flower`
2. Once flower is started, it doesn't seem to pickup any tasks: I had `celery` running, and `flower`, then started a task. Task started, and out was visible in Celery, however, no tasks showed in `flower` either during or after. Flower hadn't picked up the broker from my Django settings like it normally did. 
3. Passing `--broker` explicitly to `celery flower` didn't seem to work either, the output still showed `amqp://guest:**@localhost:5672//`

**Comment by stuaxo** [comment]
It may have been a misconfiguration on the part of my dev setup, but I needed to make sure my celery settings had

```
CELERY_BROKER_URL=redis://@localhost:6379/1
CELERY_RESULT_BACKEND=redis://@localhost:6379/0
```

Where I was missing the `@` before.

**Comment by pembo13** [comment]
@stuaxo I'll give that a try, but did you need the "@" before? What information does "@" even contribute to the URL in this case?

**Comment by stuaxo** [comment]
Celery still ran before but didn't show any tasks or jobs.

I've never seen the @ for, just guessed from the client from the other person here.

**Comment by jlost** [comment]
Eagerly awaiting a release!

**Comment by pembo13** [comment]
@mher `https://github.com/mher/flower/zipball/master#egg=flower` is basically broken for me. It ignores `CELERY_BROKER_URL` and `CELERY_RESULT_BACKEND` in my `settings.py` and starts up with "Broker: amqp://guest:**@localhost:5672//" every time.

**Comment by erikcw** [comment]
@pembo13 I noticed that it was overriding arguments passed to the `celery flower` command with environment variables.  In my case it was ignoring the `-A` argument in favor the the `APP` environment variable (which my application uses for another purpose).  I changed my startup script to use `APP=myapp celery flower -A myapp....` and it started working.

**Comment by pembo13** [comment]
@erikcw if true, that would still be a troublesome regression that would break several projects. If I get a chance, I'll test that at least this works.

**Comment by zenofewords** [comment]
I was able to circumvent the argument ignoring issue by adding `BROKER_URL = "amqp://user:password@hostname:port//"` to the `celeryconfig.py` which flower uses by default. Leaving config empty and passing `--broker` when starting flower (also tried `--broker_url`) did not work.

This was done on celery==5.0.5 and the latest dev version of flower.

**Comment by cfculhane** [comment]
Just confirming this is still an issue, everything is configured in settings but flower still wont change its broker or registered tasks...

**Comment by Romamo** [comment]
Works fine with master

**Comment by Tomasz-Kluczkowski** [comment]
@mher I had a look at the issue with `celery.bin.base` module and locally with latest master version of flower and celery 5.0.5 I do not get this issue. I am able to start celery app and flower (with `celery flower` command) and no import crashes happen.

Unfortunately other problems reported above are still there:
- `flower` command as you mentioned does not work (I use `celery flower`)
- flower ignores values passed in command line arguments (I had to create celeryconfig.py for the correct broker/backend to be used)

Should we open 2 issues for those then to separate them and start fixing?

**Comment by mher** [comment]
@Tomasz-Kluczkowski Yes, I think having separate issues makes sense

**Comment by otterbotter** [comment]
I am able to run Flower with no issues using `celery -A proj flower` and no additional configuration necessary.

Using Flower 1.0.1 and Celery 5.1.0

**Comment by hodinhtan** [comment]
> I am able to run Flower with no issues using `celery -A proj flower` and no additional configuration necessary.
> 
> Using Flower 1.0.1 and Celery 5.1.0

Can you share where you get Flower 1.0.1, as I see latest version 0.9.7.

**Comment by otterbotter** [comment]
> > I am able to run Flower with no issues using `celery -A proj flower` and no additional configuration necessary.
> > Using Flower 1.0.1 and Celery 5.1.0
> 
> Can you share where you get Flower 1.0.1, as I see latest version 0.9.7.

I installed using `pip install https://github.com/mher/flower/zipball/master#egg=flower` which reported these versions post-installation:

`Successfully installed amqp-5.0.6 billiard-3.6.4.0 celery-5.1.0 click-plugins-1.1.1 flower-1.0.1 kombu-5.1.0`

**Comment by jlost** [comment]
It would be nice to have a PyPI release of 1.0.1 so I don't have to use master or pin a specific commit for production apps.

**Comment by souvikg10** [comment]
Any plans for a PyPI release? I second the above comment. If you have a stable flower-1.0.1 as the docs pointing to flower 1.0.1 as well. Could you please also publish flower==1.0.1 to PyPI 

Thanks

**Comment by thangluu93** [comment]
Important Please note that from version 1.0.1 Flower uses Celery 5 and has to be invoked in the same style as celery commands do.

I can see important note of flower in github. And I tried $ celery -A proj flower like in doc of celery but i receive the error like this:
from celery.bin.base import Command
ImportError: cannot import name 'Command' from 'celery.bin.base'

**Comment by hosszubalazs** [comment]
Dear @mher, when can we expect a flower==1.0.1 PyPi release? Thanks for the answer!

**Comment by Kub-AT** [comment]
> I was able to circumvent the argument ignoring issue by adding `BROKER_URL = "amqp://user:password@hostname:port//"` to the `celeryconfig.py` which flower uses by default. Leaving config empty and passing `--broker` when starting flower (also tried `--broker_url`) did not work.
> 
> This was done on celery==5.0.5 and the latest dev version of flower.

Now you should pass --broker and --app to celery args no to flower args, like this:

`celery -A apps.core flower --address=0.0.0.0 --port=5566 -l INFO`

https://github.com/mher/flower/issues/1103#issuecomment-839166778

**Comment by mher** [comment]
Released a new version https://pypi.org/project/flower/1.0.0/
